### ISSUE TITLE
how Rectified Adam effect?

### ISSUE THREAD

**Issue by daixiangzi** [titu1994/keras_rectified_adam#1]
author make some experiments in other dataset??

**Comment by titu1994** [comment]
There paper has experimental results.

**Comment by daixiangzi** [comment]
i know ,i only ask you about yourself make experiment？？ 
 
---Original---

**Comment by titu1994** [comment]
I tried it out on CIFAR 10 just to see if the optimizer works. Didn't test for full training.

**Comment by daixiangzi** [comment]
i think you should try to train all data,its  effect could be exaggerated


 
---Original---

**Comment by titu1994** [comment]
I don't have the time or the compute. You are free to try it.

**Comment by daixiangzi** [comment]
ok


 
---Original---
